# Generated by Django 2.2.5 on 2019-09-25 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_published',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
