# Generated by Django 2.2.5 on 2019-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('comments', models.TextField()),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
